// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Go One
Go One API


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0
    Contact: Go One API Support

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
